aSalvoV0.2/config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "welcome#index"
  resources :users do
      resources :contacts
      resources :emergencies
  end

  resources :entities

end

aSalvoV0.2/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

aSalvoV0.2/app/models/contact.rb
class Contact < ApplicationRecord
  has_and_belongs_to_many :users
end

aSalvoV0.2/app/models/emergency.rb
class Emergency < ApplicationRecord
  belongs_to :user
  belongs_to :entity
end

aSalvoV0.2/app/models/entity.rb
class Entity < ApplicationRecord
  has_many :emergencies
  has_many :users, :through => :emergencies
end

aSalvoV0.2/app/models/user.rb
class User < ApplicationRecord
  has_and_belongs_to_many :contacts
  has_many :emergencies
  has_many :entities, :through => :emergencies
end

aSalvoV0.2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

aSalvoV0.2/app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
    @user=User.find(params[:user_id])
    @contact=@user.contacts.all
  end
  def new
    @user=User.find(params[:user_id])
    @contact=@user.contacts.build #prepara la variable para recibir los datos del formulario New Contact
  end
  def create
    @user=User.find(params[:user_id])
    @contact=Contact.new(contact_params) #crea el objeto con los parámetros permitidos.
    if @contact.save
      @user.contacts << @contact #realiza la asignaciòn utilizando el has and belongs to many
      flash[:notice]="Se ha creado el contacto"
      redirect_to @user
    else
      flash[:error]="No se ha creado el contacto"
      render action:"new"
    end
  end
  def show
    @user=User.find(params[:user_id])
    @contact=@user.contacts.find(params[:id])
  end
  def edit

  end
  def update

  end
  def destroy

  end
  private
    def contact_params
      params.require(:contact).permit(:contacto_nombre,:contacto_cel,:contacto_mail)
    end
end

aSalvoV0.2/app/controllers/emergencies_controller.rb
class EmergenciesController < ApplicationController
  def index

  end
  def new
    @user=User.find(params[:user_id])
    @user.entities.new
    @emergency=@user.emergencies.build
  end
  def create
    @user=User.find(params[:user_id])
    @emergency=Emergency.new(emergency_params)
    if @emergency.save
      @user.emergency << @emergency #realiza la asignaciòn utiliz
      flash[:notice]="Se ha creado la emergencia"
      redirect_to @user
    else
      flash[:error]="No se ha creado emergencia"
      render action:"new"
    end
  end
  def show
    @user=User.find(params[:user_id])
    @emergency=@user.emergencies.find(params[:id])
  end
  def edit

  end
  def update

  end
  def destroy

  end
  private
  def emergency_params
    params.require(:emergency).permit(:emergencia_fecha,:emergencia_ubicacion,:emergencia_data)
  end
end

aSalvoV0.2/app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  def index
    @entity=Entity.all
  end
  def new
    @entity=Entity.new
  end
  def create
    @entity=Entity.new(entity_params)
    if @entity.save
      flash[:notice]="Se ha creado la entidad"
      redirect_to @entity
    else
      flash[:error]="No se ha creado la entidad"
      render action:"new"
    end
  end
  def show
    @entity=Entity.find(params[:id])
  end
  def edit
    @entity=Entity.find(params[:id])
  end
  def update
    @entity = Entity.find(params[:id])
    if @entity.update(entity_params)
      flash[:notice]="Se ha actualizado la entidad"
      redirect_to @entity
    else
      flash[:error]="No se ha actualizado la entidad"
      render action: "edit"
    end
  end
  def destroy
    @entity=Entity.find(params[:id])
    @entity.destroy
    flash[:notice]= "La entidad se ha eliminado"
    redirect_to entities_path
  end
  private
    def entity_params
      params.require(:entity).permit(:entidad_nombre,:entidad_representante,:entidad_tel,:entidad_email,:entidad_dir,:password_digest)
    end
end

aSalvoV0.2/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users=User.all
  end
  def new
    @user=User.new
  end
  def create
    @user = User.new(user_params)
      if @user.save
        flash[:notice]="Se ha creado el usuario."
        redirect_to @user
      else
        flash[:error]="No se ha creado el usuario."
        render action: "new"
      end
  end
  def show
    @user=User.find(params[:id])
  end
  def edit
    @user=User.find(params[:id])
  end
  def update
    @user=User.find(params[:id])
      if @user.update(user_params)
        flash[:notice]="Se ha actualizado el usuario"
        redirect_to @user
      else
        flash[:error]="No se ha actualizado el usuario"
        render action:"edit"
      end
  end
  def destroy
    @user=User.find(params[:id])
    @user.destroy
    flash[:notice]="El usuario se ha eliminado"
    redirect_to users_path
  end
  private
    def user_params
      params.require(:user).permit(:usuario_nombre,:usuario_apellido,:usuario_mail,:usuario_cel,:usuario_sexo,:usuario_fechaNacimiento,:usuario_ubicacion,:password_digest)
    end
end

aSalvoV0.2/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    
  end
end

aSalvoV0.2/app/helpers/application_helper.rb
module ApplicationHelper
end

aSalvoV0.2/app/helpers/contacts_helper.rb
module ContactsHelper
end

aSalvoV0.2/app/helpers/emergencies_helper.rb
module EmergenciesHelper
end

aSalvoV0.2/app/helpers/entities_helper.rb
module EntitiesHelper
end

aSalvoV0.2/app/helpers/users_helper.rb
module UsersHelper
end

aSalvoV0.2/app/helpers/welcome_helper.rb
module WelcomeHelper
end

aSalvoV0.2/app/views/contacts/edit.html.erb
<%= form_for(@contact) do |f|%>
  <%= f.label :contacto_nombre %>
  <%= f.text_field :contacto_nombre %>
  <%= f.label :contacto_cel%>
  <%= f.text_field :contacto_cel%>
  <%= f.label :contacto_mail%>
  <%= f.text_field :contacto_mail%>
  <%= f.submit "Guardar"%>
<% end %>

aSalvoV0.2/app/views/contacts/index.html.erb
<br/>

<% @user.contacts.each do |contact|%>
  <%= link_to @user.contact, contact%><br/>
<%end%>

aSalvoV0.2/app/views/contacts/new.html.erb
<%= form_for [@user,@contact] do |f|%>
  <%= f.label :contacto_nombre %>
  <%= f.text_field :contacto_nombre %><br/>
  <%= f.label :contacto_cel%>
  <%= f.text_field :contacto_cel%><br/>
  <%= f.label :contacto_mail%>
  <%= f.text_field :contacto_mail%><br/>
  <%= f.submit "Guardar"%>
<% end %>

aSalvoV0.2/app/views/contacts/show.html.erb
<h2><%=@contact.contacto_nombre%><br></h2>
<strong>Tel:</strong> <%=@contact.contacto_cel%><br>
<strong>Mail:</strong> <%=@contact.contacto_mail%><br>

aSalvoV0.2/app/views/emergencies/new.html.erb
<%= form_for [@user,@emergency] do |f| %>
  <%= f.label :emergencia_fecha%>
  <%= f.text_field :emergencia_fecha%><br/>
  <%= f.label :emergencia_ubicacion%>
  <%= f.text_field :emergencia_ubicacion%><br/>
  <%= f.label :emergencia_data%>
  <%= f.text_field :emergencia_data%><br/>
  <%= f.submit "Guardar" %>
<% end%>

aSalvoV0.2/app/views/entities/edit.html.erb
<%= form_for(@entity) do |f| %>
  <%= f.label :entidad_nombre %>
  <%= f.text_field :entidad_nombre %><br/>
  <%= f.label :entidad_representante %>
  <%= f.text_field :entidad_representante %><br/>
  <%= f.label :entidad_tel %>
  <%= f.text_field :entidad_tel %><br/>
  <%= f.label :entidad_email %>
  <%= f.text_field :entidad_email %><br/>
  <%= f.label :entidad_dir %>
  <%= f.text_field :entidad_dir %><br/>
  <%= f.label :password_digest %>
  <%= f.text_field :password_digest %><br/>
  <%= f.submit "Guardar" %>
<% end %>

aSalvoV0.2/app/views/entities/index.html.erb
<%= link_to "Nueva Entidad", new_entity_path%><br/>
<% @entity.each do |entity|%>
  <%= link_to entity.entidad_nombre,entity%><br/>
<% end %>

aSalvoV0.2/app/views/entities/new.html.erb
<%= form_for(@entity) do |f| %>
  <%= f.label :entidad_nombre %>
  <%= f.text_field :entidad_nombre %><br/>
  <%= f.label :entidad_representante %>
  <%= f.text_field :entidad_representante %><br/>
  <%= f.label :entidad_tel %>
  <%= f.text_field :entidad_tel %><br/>
  <%= f.label :entidad_email %>
  <%= f.text_field :entidad_email %><br/>
  <%= f.label :entidad_dir %>
  <%= f.text_field :entidad_dir %><br/>
  <%= f.label :password_digest %>
  <%= f.text_field :password_digest %><br/>
  <%= f.submit "Guardar" %>
<% end %>

aSalvoV0.2/app/views/entities/show.html.erb
<h1><%= @entity.entidad_nombre%></h1>
<ul>
  <li>Representante: <%=@entity.entidad_representante%></li>
  <li>Teléfono: <%=@entity.entidad_tel%></li>
  <li>E-mail: <%=@entity.entidad_email%></li>
  <li>Dirección: <%=@entity.entidad_dir%></li>
</ul>
<%= link_to "Editar", edit_entity_path(@entity) %><br/>
<%= link_to "Eliminar", entity_path(@entity), method: :delete, data:{confirm:"¿Estás Seguro?, esta acción no se puede deshacer"}%><br/> <!--popup de confirmación-->

aSalvoV0.2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>aSalvo V0.2</title>
    <link href="https://fonts.googleapis.com/css?family=Roboto+Slab|Roboto:300i" rel="stylesheet">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <header class="cabecera">
    <div class="social_header">
      <i class="fab fa-twitter iconleft"></i>
      <i class="fab fa-facebook-f iconleft"></i>
      <i class="fab fa-instagram iconleft"></i>
      <a href="users"><i class="far fa-user iconright"></i></a>
      <i class="fas fa-search iconright"></i>
    </div>
    <nav id="mainNav">
     <ul class="no-list row">
      <li class="col-md">
       <%= link_to "Denuncia!", root_path,class:"denuncia"%>
      </li>
      <li class="col-md">
       <%= link_to "Apoyo", root_path%>
      </li>
      <li class="col-md">
       <%= link_to "Educación", root_path%>
      </li>
      <li>
        <%= image_tag 'logo.png',class:"logo"%>
      </li>
      <li class="col-md">
       <%= link_to "Meetups", root_path%>
      </li>
      <li class="col-md">
       <%= link_to "Encuesta", root_path%>
      </li>
      <li class="col-md">
       <%= link_to "Contáctenos", root_path%>
     </li>
     </ul>
    </nav>
  </header>
  <%= yield %>
  <footer>
    <div>
      <p>&copy; aSalvo 2018. All Rights Reserved.</p>
      <ul class="list-inline">
        <li class="list-inline-item">
          <a href="#">Privacy</a>
        </li>
        <li class="list-inline-item">
          <a href="#">Terms</a>
        </li>
        <li class="list-inline-item">
          <a href="#">FAQ</a>
        </li>
      </ul>
    </div>
  </footer>
  </body>
</html>

aSalvoV0.2/app/views/users/edit.html.erb
<%= form_for(@user) do |f| %>
  <%= f.label :usuario_nombre %>
  <%= f.text_field :usuario_nombre %><br/>
  <%= f.label :usuario_apellido %>
  <%= f.text_field :usuario_apellido %><br/>
  <%= f.label :usuario_mail %>
  <%= f.text_field :usuario_mail %><br/>
  <%= f.label :usuario_cel %>
  <%= f.text_field :usuario_cel %><br/>
  <%= f.label :usuario_sexo %>
  <%= f.text_field :usuario_sexo %><br/>
  <%= f.label :usuario_fechaNacimiento %>
  <%= f.text_field :usuario_fechaNacimiento %><br/>
  <%= f.label :usuario_ubicacion %>
  <%= f.text_field :usuario_ubicacion %><br/>
  <%= f.label :password_digest %>
  <%= f.text_field :password_digest %><br/>
  <%= f.submit "Guardar" %>
<% end %>

aSalvoV0.2/app/views/users/index.html.erb
<%= link_to "Nuevo Usuario", new_user_path%><br/>

<% @users.each do |user|%>
  <%= link_to user.usuario_nombre+" "+user.usuario_apellido,user %><br/>
<% end %>

aSalvoV0.2/app/views/users/new.html.erb
<%= form_for(@user) do |f| %>
  <%= f.label :usuario_nombre %>
  <%= f.text_field :usuario_nombre %><br/>
  <%= f.label :usuario_apellido %>
  <%= f.text_field :usuario_apellido %><br/>
  <%= f.label :usuario_mail %>
  <%= f.text_field :usuario_mail %><br/>
  <%= f.label :usuario_cel %>
  <%= f.text_field :usuario_cel %><br/>
  <%= f.label :usuario_sexo %>
  <%= f.text_field :usuario_sexo %><br/>
  <%= f.label :usuario_fechaNacimiento %>
  <%= f.text_field :usuario_fechaNacimiento %><br/>
  <%= f.label :usuario_ubicacion %>
  <%= f.text_field :usuario_ubicacion %><br/>
  <%= f.label :password_digest %>
  <%= f.text_field :password_digest %><br/>
  <%= f.submit "Guardar" %>
<% end %>

aSalvoV0.2/app/views/users/show.html.erb
<h1><%= @user.usuario_nombre+" "+@user.usuario_apellido %></h1>
<ul>
  <li>Correo: <%=@user.usuario_mail%></li>
  <li>Cel: <%=@user.usuario_cel%></li>
  <li>Sexo: <%=@user.usuario_sexo%></li>
  <li>Fecha de Nacimiento: <%=@user.usuario_fechaNacimiento%></li>
  <li>Ubicación: <%=@user.usuario_ubicacion%></li>
</ul>
<%= link_to "Editar", edit_user_path(@user) %><br/>
<%= link_to "Eliminar", user_path(@user), method: :delete, data:{confirm:"¿Estás Seguro?, esta acción no se puede deshacer"}%><br/>
<br/>
<br/>
<h1>Contactos</h1>
<% @user.contacts.each do |contact| %>
  <%= link_to contact.contacto_nombre, [@user,contact] %><br/>
<% end %>

<%= link_to "Añadir contacto", new_user_contact_path(@user) %><br/>
<h1>Emergencias</h1>
<% @user.emergencies.each do |emergency| %>
  <%= link_to emergency.emergencia_date, [@user,emergency] %><br/>
<% end %>
<%= link_to "Crear emergencia", new_user_emergency_path(@user) %><br/>

aSalvoV0.2/app/views/welcome/index.html.erb
<section class="masthead">
  <div class="wrapper">
    <div class="container-fluid">
      <%= image_tag("girl_2.jpg",class:"welcome") %>
    </div>
    <div class="cuadro-mensaje">
      <h2>Queremos verte <strong>ASalvo!</strong></h2><br/>
      <button type="button" class="btn btn-light "><a href="#playstore">Descargar</a></button>
    </div>
  </div>
  <%= yield %>
</section>